-- Consolidated initial schema.
--
-- Generated by `pg_dump --schema-only --no-owner --no-privileges --no-comments`
-- against a fresh DB after applying the prior 35 numbered migrations
-- (001 → 043, with gaps), then normalized to drop the dump preamble.
-- The repository policy is "no backwards compatibility" (see CLAUDE.md):
-- early-stage churn squashes its own history rather than carrying forward
-- compatibility shims. New migrations resume at 003 and apply on top of
-- this init + 002_seed_system_data.sql.
--
-- Update procedure: when this file is wrong, do NOT add a fix-up migration.
-- Edit this file in place. If the change is non-trivial, repeat the squash
-- process (apply the dirty migration set to a fresh DB, pg_dump, normalize,
-- replace) so the file stays an honest snapshot.


-- Name: admin_mcp_servers; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.admin_mcp_servers (
    server_id text NOT NULL,
    tenant_id text NOT NULL,
    server_name text NOT NULL,
    description text,
    transport_kind text DEFAULT 'http'::text NOT NULL,
    mode text NOT NULL,
    route_path text NOT NULL,
    upstream_url text,
    headers_allowlist jsonb DEFAULT '[]'::jsonb NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    config_hash text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_by text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_published boolean DEFAULT true NOT NULL
);

-- Name: admin_skill_revisions; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.admin_skill_revisions (
    skill_revision_id bigint NOT NULL,
    tenant_id text NOT NULL,
    skill_id text NOT NULL,
    revision_number bigint NOT NULL,
    source_type text NOT NULL,
    source_label text,
    bundle_name text,
    bundle_hash text NOT NULL,
    validation_status text DEFAULT 'pending'::text NOT NULL,
    validation_messages jsonb DEFAULT '[]'::jsonb NOT NULL,
    review_status text DEFAULT 'pending_review'::text NOT NULL,
    review_notes text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    reviewed_by text,
    reviewed_at timestamp with time zone,
    activated_at timestamp with time zone,
    bundle_storage_uri text
);

-- Name: admin_skill_revisions_skill_revision_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.admin_skill_revisions_skill_revision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: admin_skill_revisions_skill_revision_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.admin_skill_revisions_skill_revision_id_seq OWNED BY public.admin_skill_revisions.skill_revision_id;

-- Name: admin_skills; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.admin_skills (
    skill_id text NOT NULL,
    tenant_id text NOT NULL,
    skill_name text NOT NULL,
    description text,
    version bigint DEFAULT 1 NOT NULL,
    active_revision_id bigint,
    enabled boolean DEFAULT true NOT NULL,
    created_by text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_published boolean DEFAULT true NOT NULL
);

-- Name: approvals; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.approvals (
    id bigint NOT NULL,
    approval_id text NOT NULL,
    tenant_id text NOT NULL,
    session_id text NOT NULL,
    user_id text NOT NULL,
    runtime_id text NOT NULL,
    turn_id text NOT NULL,
    item_id text NOT NULL,
    request_method text NOT NULL,
    request_id text NOT NULL,
    kind text NOT NULL,
    title text NOT NULL,
    summary text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    decision text,
    request_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    -- Wall-clock deadline after which a still-`pending` approval is stale and
    -- must be swept to `status='expired'`. In-process TTL timers normally fire
    -- first; this column is the DB-level backstop that a startup sweep uses to
    -- recover rows orphaned by a crash/restart before the timer could run.
    expires_at timestamp with time zone NOT NULL
);

-- Name: approvals_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.approvals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: approvals_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.approvals_id_seq OWNED BY public.approvals.id;

-- Name: artifact_download_tokens; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.artifact_download_tokens (
    id bigint NOT NULL,
    token text NOT NULL,
    tenant_id text NOT NULL,
    artifact_id text NOT NULL,
    session_id text NOT NULL,
    user_id text NOT NULL,
    storage_backend text NOT NULL,
    storage_key text NOT NULL,
    file_name text NOT NULL,
    content_type text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: artifact_download_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.artifact_download_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: artifact_download_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.artifact_download_tokens_id_seq OWNED BY public.artifact_download_tokens.id;

-- Name: artifacts; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.artifacts (
    id bigint NOT NULL,
    artifact_id text NOT NULL,
    tenant_id text NOT NULL,
    session_id text NOT NULL,
    user_id text NOT NULL,
    artifact_type text NOT NULL,
    source_artifact_id text,
    artifact_name text NOT NULL,
    mime_type text NOT NULL,
    storage_backend text NOT NULL,
    storage_key text NOT NULL,
    file_size_bytes bigint DEFAULT 0 NOT NULL,
    checksum_sha256 text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    created_by_type text DEFAULT 'user'::text NOT NULL,
    created_by_ref text,
    detail_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: artifacts_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.artifacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: artifacts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.artifacts_id_seq OWNED BY public.artifacts.id;

-- Name: audit_events; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.audit_events (
    id bigint NOT NULL,
    tenant_id text NOT NULL,
    session_id text,
    -- Nullable so the FK can be ON DELETE SET NULL: the audit trail is an
    -- append-only forensic record and MUST outlive the user/session it
    -- references. Deleting a user nulls the reference here rather than
    -- cascade-deleting their audit history (which would be a track-covering
    -- vector and break forensic continuity).
    user_id text,
    approval_id text,
    event_type text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    ip_address inet,
    user_agent text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: audit_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.audit_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: audit_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.audit_events_id_seq OWNED BY public.audit_events.id;

-- Name: message_tool_results; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.message_tool_results (
    id bigint NOT NULL,
    tool_result_id text NOT NULL,
    tenant_id text NOT NULL,
    message_id text NOT NULL,
    session_id text NOT NULL,
    user_id text NOT NULL,
    kind text NOT NULL,
    title text NOT NULL,
    status text NOT NULL,
    server_name text DEFAULT ''::text NOT NULL,
    tool_name text DEFAULT ''::text NOT NULL,
    command_text text DEFAULT ''::text NOT NULL,
    input_text text DEFAULT ''::text NOT NULL,
    cwd text DEFAULT ''::text NOT NULL,
    output_text text DEFAULT ''::text NOT NULL,
    exit_code integer,
    duration_ms integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: message_tool_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.message_tool_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: message_tool_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.message_tool_results_id_seq OWNED BY public.message_tool_results.id;

-- Name: messages; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.messages (
    id bigint NOT NULL,
    message_id text NOT NULL,
    tenant_id text NOT NULL,
    session_id text NOT NULL,
    user_id text NOT NULL,
    role text NOT NULL,
    status text NOT NULL,
    content_text text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    input_tokens integer,
    cached_input_tokens integer,
    output_tokens integer,
    reasoning_output_tokens integer,
    total_tokens integer,
    model_name text,
    cost_usd numeric(12,8),
    feedback_rating text,
    feedback_notes text,
    feedback_given_at timestamp with time zone,
    reasoning_content text DEFAULT ''::text NOT NULL,
    plan_content text DEFAULT ''::text NOT NULL,
    detail_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT messages_feedback_rating_check CHECK ((feedback_rating = ANY (ARRAY['thumbs_up'::text, 'thumbs_down'::text])))
);

-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.messages_id_seq OWNED BY public.messages.id;

-- Name: pii_scan_jobs; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.pii_scan_jobs (
    tenant_id text NOT NULL,
    job_id text NOT NULL,
    scan_run_id text NOT NULL,
    subject_type text NOT NULL,
    subject_id text NOT NULL,
    source_session_id text,
    source_user_id text,
    mode text NOT NULL,
    payload_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 3 NOT NULL,
    run_after timestamp with time zone DEFAULT now() NOT NULL,
    claimed_at timestamp with time zone,
    completed_at timestamp with time zone,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT pii_scan_jobs_mode_check CHECK ((mode = ANY (ARRAY['detect'::text, 'block'::text, 'transform'::text]))),
    CONSTRAINT pii_scan_jobs_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'claimed'::text, 'completed'::text, 'failed'::text]))),
    CONSTRAINT pii_scan_jobs_subject_type_check CHECK ((subject_type = ANY (ARRAY['message'::text, 'artifact'::text])))
);

-- Name: pii_scan_runs; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.pii_scan_runs (
    tenant_id text NOT NULL,
    scan_run_id text NOT NULL,
    subject_type text NOT NULL,
    subject_id text NOT NULL,
    source_session_id text,
    source_user_id text,
    mode text NOT NULL,
    provider_type text,
    provider_model text,
    status text DEFAULT 'pending'::text NOT NULL,
    findings_json jsonb DEFAULT '[]'::jsonb NOT NULL,
    summary_text text,
    action_taken text,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT pii_scan_runs_mode_check CHECK ((mode = ANY (ARRAY['off'::text, 'detect'::text, 'block'::text, 'transform'::text]))),
    CONSTRAINT pii_scan_runs_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'blocked'::text, 'transformed'::text]))),
    CONSTRAINT pii_scan_runs_subject_type_check CHECK ((subject_type = ANY (ARRAY['message'::text, 'artifact'::text])))
);

-- Name: platform_events; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.platform_events (
    id bigint NOT NULL,
    event_type text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: platform_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.platform_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: platform_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.platform_events_id_seq OWNED BY public.platform_events.id;

-- Name: resource_activations; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.resource_activations (
    id bigint NOT NULL,
    tenant_id text NOT NULL,
    session_id text NOT NULL,
    message_id text,
    resource_type text NOT NULL,
    resource_id text NOT NULL,
    event_type text NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT resource_activations_event_type_check CHECK ((event_type = ANY (ARRAY['materialized'::text, 'invoked'::text, 'failed'::text]))),
    CONSTRAINT resource_activations_resource_type_check CHECK ((resource_type = ANY (ARRAY['skill'::text, 'mcp_server'::text, 'integration'::text])))
);

-- Name: resource_activations_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.resource_activations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: resource_activations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.resource_activations_id_seq OWNED BY public.resource_activations.id;

-- Name: runtime_sessions; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.runtime_sessions (
    id bigint NOT NULL,
    session_id text NOT NULL,
    tenant_id text NOT NULL,
    user_id text NOT NULL,
    runtime_id text NOT NULL,
    workspace_path text NOT NULL,
    status text DEFAULT 'inactive'::text NOT NULL,
    health_status text DEFAULT 'unknown'::text NOT NULL,
    codex_version text NOT NULL,
    codex_schema_version text DEFAULT 'v2'::text NOT NULL,
    manifest_path text DEFAULT ''::text NOT NULL,
    manifest_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    lifecycle_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_active_at timestamp with time zone,
    started_at timestamp with time zone,
    terminated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    runtime_provider text DEFAULT 'codex'::text NOT NULL
);

-- Name: runtime_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.runtime_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: runtime_sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.runtime_sessions_id_seq OWNED BY public.runtime_sessions.id;

-- Name: scheduled_job_runs; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.scheduled_job_runs (
    run_id text NOT NULL,
    tenant_id text NOT NULL,
    job_id text NOT NULL,
    user_id text NOT NULL,
    session_id text,
    status text DEFAULT 'pending'::text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    duration_ms integer,
    input_tokens integer DEFAULT 0 NOT NULL,
    output_tokens integer DEFAULT 0 NOT NULL,
    error_message text,
    summary text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: scheduled_jobs; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.scheduled_jobs (
    job_id text NOT NULL,
    tenant_id text NOT NULL,
    user_id text NOT NULL,
    job_name text NOT NULL,
    description text,
    schedule_kind text DEFAULT 'cron'::text NOT NULL,
    cron_expression text NOT NULL,
    time_zone text NOT NULL,
    target_type text DEFAULT 'prompt'::text NOT NULL,
    target_ref text,
    input_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    settings_snapshot_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    -- Consecutive failed runs since the last success. The scheduler worker
    -- auto-disables a job once this reaches SCHEDULER_MAX_CONSECUTIVE_FAILURES
    -- so a poison job can't re-fire every tick forever; reset to 0 on success.
    consecutive_failures integer DEFAULT 0 NOT NULL,
    last_run_at timestamp with time zone,
    next_run_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- (schema_migrations is created by the migration runner itself; see
-- src/scripts/migrate.ts. Intentionally not declared here.)

-- Name: session_runtime_overrides; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.session_runtime_overrides (
    tenant_id text NOT NULL,
    session_id text NOT NULL,
    runtime_provider text,
    enabled_tool_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    enabled_mcp_server_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    enabled_skill_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    approval_policy text DEFAULT 'never'::text NOT NULL,
    auto_approve_read_only_tools boolean DEFAULT true NOT NULL,
    created_by text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: sessions; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.sessions (
    session_id text NOT NULL,
    tenant_id text NOT NULL,
    user_id text NOT NULL,
    session_name text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    purpose text DEFAULT 'normal'::text NOT NULL
);

-- Name: tenant_integrations; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.tenant_integrations (
    tenant_id text NOT NULL,
    integration_id text NOT NULL,
    reads_enabled boolean DEFAULT false NOT NULL,
    writes_enabled boolean DEFAULT false NOT NULL,
    config_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by text
);

-- Name: tenant_memberships; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.tenant_memberships (
    tenant_id text NOT NULL,
    user_id text NOT NULL,
    role text DEFAULT 'member'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_beta_tester boolean DEFAULT false NOT NULL
);

-- Name: tenant_org_settings; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.tenant_org_settings (
    tenant_id text NOT NULL,
    openai_api_key_encrypted text,
    anthropic_api_key_encrypted text,
    skill_marketplace_manifest_url text,
    pii_protection jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: tenant_settings; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.tenant_settings (
    tenant_id text NOT NULL,
    approval_policy text DEFAULT 'on-request'::text NOT NULL,
    approval_reviewer text DEFAULT 'user'::text NOT NULL,
    allow_command_execution boolean DEFAULT false NOT NULL,
    allow_user_token_forwarding boolean DEFAULT true NOT NULL,
    auto_approve_read_only_tools boolean DEFAULT true NOT NULL,
    policy_enforcement_mode text DEFAULT 'monitor'::text NOT NULL,
    developer_instructions text,
    enabled_tool_ids jsonb DEFAULT '["managed-session-context", "session_context", "list_artifacts", "read_text_artifact", "read_skill_corpus", "write_artifact"]'::jsonb NOT NULL,
    enabled_mcp_server_ids jsonb DEFAULT '["managed-session-context"]'::jsonb NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    config_hash text DEFAULT ''::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    enabled_runtime_providers jsonb DEFAULT '["codex"]'::jsonb NOT NULL,
    show_effort_selector boolean DEFAULT false NOT NULL,
    web_search_mode text DEFAULT 'disabled'::text NOT NULL,
    CONSTRAINT tenant_settings_policy_enforcement_mode_check CHECK ((policy_enforcement_mode = ANY (ARRAY['monitor'::text, 'enforce'::text]))),
    CONSTRAINT tenant_settings_web_search_mode_check CHECK ((web_search_mode = ANY (ARRAY['disabled'::text, 'cached'::text, 'live'::text])))
);

-- Name: tenants; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.tenants (
    tenant_id text NOT NULL,
    tenant_name text NOT NULL,
    slug text NOT NULL,
    sso_provider text,
    sso_connection_id text,
    workos_org_id text,
    plan text DEFAULT 'free'::text NOT NULL,
    custom_domain text,
    settings_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: tool_events; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.tool_events (
    id bigint NOT NULL,
    tenant_id text NOT NULL,
    session_id text NOT NULL,
    user_id text NOT NULL,
    message_id text,
    runtime_id text NOT NULL,
    approval_id text,
    tool_call_id text NOT NULL,
    kind text NOT NULL,
    title text NOT NULL,
    phase text NOT NULL,
    status text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    duration_ms integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: tool_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.tool_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: tool_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.tool_events_id_seq OWNED BY public.tool_events.id;

-- Name: tool_execution_contexts; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.tool_execution_contexts (
    id bigint NOT NULL,
    tool_context_id text NOT NULL,
    tenant_id text NOT NULL,
    session_id text NOT NULL,
    user_id text NOT NULL,
    runtime_id text NOT NULL,
    runtime_policy_id text,
    message_id text,
    credential_envelope jsonb DEFAULT '{}'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: tool_execution_contexts_id_seq; Type: SEQUENCE; Schema: public; Owner: -

CREATE SEQUENCE public.tool_execution_contexts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: tool_execution_contexts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -

ALTER SEQUENCE public.tool_execution_contexts_id_seq OWNED BY public.tool_execution_contexts.id;

-- Name: user_github_connections; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.user_github_connections (
    tenant_id text NOT NULL,
    user_id text NOT NULL,
    github_user_id text NOT NULL,
    github_login text NOT NULL,
    github_name text,
    github_email text,
    github_avatar_url text,
    token_type text DEFAULT 'bearer'::text NOT NULL,
    granted_scopes jsonb DEFAULT '[]'::jsonb NOT NULL,
    access_token_encrypted text NOT NULL,
    access_token_expires_at timestamp with time zone,
    refresh_token_encrypted text,
    refresh_token_expires_at timestamp with time zone,
    github_token_last_refreshed_at timestamp with time zone,
    github_token_last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: user_microsoft_connections; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.user_microsoft_connections (
    tenant_id text NOT NULL,
    user_id text NOT NULL,
    microsoft_user_id text NOT NULL,
    microsoft_email text,
    microsoft_display_name text,
    token_type text DEFAULT 'bearer'::text NOT NULL,
    granted_scopes jsonb DEFAULT '[]'::jsonb NOT NULL,
    access_token_encrypted text NOT NULL,
    access_token_expires_at timestamp with time zone,
    refresh_token_encrypted text,
    refresh_token_expires_at timestamp with time zone,
    microsoft_token_last_refreshed_at timestamp with time zone,
    microsoft_token_last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: user_notion_connections; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.user_notion_connections (
    tenant_id text NOT NULL,
    user_id text NOT NULL,
    notion_user_id text NOT NULL,
    notion_workspace_id text,
    notion_workspace_name text,
    notion_workspace_icon text,
    notion_bot_id text,
    notion_owner_email text,
    notion_owner_name text,
    token_type text DEFAULT 'bearer'::text NOT NULL,
    granted_scopes jsonb DEFAULT '[]'::jsonb NOT NULL,
    access_token_encrypted text NOT NULL,
    access_token_expires_at timestamp with time zone,
    refresh_token_encrypted text,
    refresh_token_expires_at timestamp with time zone,
    notion_token_last_refreshed_at timestamp with time zone,
    notion_token_last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: user_settings_sections; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.user_settings_sections (
    tenant_id text NOT NULL,
    user_id text NOT NULL,
    section_key text NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    config_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: users; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.users (
    user_id text NOT NULL,
    email text,
    display_name text,
    workos_user_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: admin_skill_revisions skill_revision_id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin_skill_revisions ALTER COLUMN skill_revision_id SET DEFAULT nextval('public.admin_skill_revisions_skill_revision_id_seq'::regclass);

-- Name: approvals id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.approvals ALTER COLUMN id SET DEFAULT nextval('public.approvals_id_seq'::regclass);

-- Name: artifact_download_tokens id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifact_download_tokens ALTER COLUMN id SET DEFAULT nextval('public.artifact_download_tokens_id_seq'::regclass);

-- Name: artifacts id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifacts ALTER COLUMN id SET DEFAULT nextval('public.artifacts_id_seq'::regclass);

-- Name: audit_events id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.audit_events ALTER COLUMN id SET DEFAULT nextval('public.audit_events_id_seq'::regclass);

-- Name: message_tool_results id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.message_tool_results ALTER COLUMN id SET DEFAULT nextval('public.message_tool_results_id_seq'::regclass);

-- Name: messages id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.messages ALTER COLUMN id SET DEFAULT nextval('public.messages_id_seq'::regclass);

-- Name: platform_events id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.platform_events ALTER COLUMN id SET DEFAULT nextval('public.platform_events_id_seq'::regclass);

-- Name: resource_activations id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.resource_activations ALTER COLUMN id SET DEFAULT nextval('public.resource_activations_id_seq'::regclass);

-- Name: runtime_sessions id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.runtime_sessions ALTER COLUMN id SET DEFAULT nextval('public.runtime_sessions_id_seq'::regclass);

-- Name: tool_events id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_events ALTER COLUMN id SET DEFAULT nextval('public.tool_events_id_seq'::regclass);

-- Name: tool_execution_contexts id; Type: DEFAULT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_execution_contexts ALTER COLUMN id SET DEFAULT nextval('public.tool_execution_contexts_id_seq'::regclass);

-- Name: admin_mcp_servers admin_mcp_servers_tenant_server_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin_mcp_servers
    ADD CONSTRAINT admin_mcp_servers_tenant_server_id_key UNIQUE (tenant_id, server_id);

-- Name: admin_skill_revisions admin_skill_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin_skill_revisions
    ADD CONSTRAINT admin_skill_revisions_pkey PRIMARY KEY (skill_revision_id);

-- Name: admin_skill_revisions admin_skill_revisions_tenant_skill_revision_number_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin_skill_revisions
    ADD CONSTRAINT admin_skill_revisions_tenant_skill_revision_number_key UNIQUE (tenant_id, skill_id, revision_number);

-- Name: admin_skills admin_skills_tenant_skill_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin_skills
    ADD CONSTRAINT admin_skills_tenant_skill_id_key UNIQUE (tenant_id, skill_id);

-- Name: approvals approvals_approval_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_approval_id_key UNIQUE (approval_id);

-- Name: approvals approvals_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_pkey PRIMARY KEY (id);

-- Name: artifact_download_tokens artifact_download_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifact_download_tokens
    ADD CONSTRAINT artifact_download_tokens_pkey PRIMARY KEY (id);

-- Name: artifact_download_tokens artifact_download_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifact_download_tokens
    ADD CONSTRAINT artifact_download_tokens_token_key UNIQUE (token);

-- Name: artifacts artifacts_artifact_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_artifact_id_key UNIQUE (artifact_id);

-- Name: artifacts artifacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_pkey PRIMARY KEY (id);

-- Name: audit_events audit_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);

-- Name: message_tool_results message_tool_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.message_tool_results
    ADD CONSTRAINT message_tool_results_pkey PRIMARY KEY (id);

-- Name: message_tool_results message_tool_results_tool_result_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.message_tool_results
    ADD CONSTRAINT message_tool_results_tool_result_id_key UNIQUE (tool_result_id);

-- Name: messages messages_message_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_message_id_key UNIQUE (message_id);

-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

-- Name: pii_scan_jobs pii_scan_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.pii_scan_jobs
    ADD CONSTRAINT pii_scan_jobs_pkey PRIMARY KEY (job_id);

-- Name: pii_scan_runs pii_scan_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.pii_scan_runs
    ADD CONSTRAINT pii_scan_runs_pkey PRIMARY KEY (scan_run_id);

-- Name: platform_events platform_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.platform_events
    ADD CONSTRAINT platform_events_pkey PRIMARY KEY (id);

-- Name: resource_activations resource_activations_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.resource_activations
    ADD CONSTRAINT resource_activations_pkey PRIMARY KEY (id);

-- Name: runtime_sessions runtime_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.runtime_sessions
    ADD CONSTRAINT runtime_sessions_pkey PRIMARY KEY (id);

-- Name: runtime_sessions runtime_sessions_runtime_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.runtime_sessions
    ADD CONSTRAINT runtime_sessions_runtime_id_key UNIQUE (runtime_id);

-- Name: scheduled_job_runs scheduled_job_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.scheduled_job_runs
    ADD CONSTRAINT scheduled_job_runs_pkey PRIMARY KEY (run_id);

-- Name: scheduled_jobs scheduled_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.scheduled_jobs
    ADD CONSTRAINT scheduled_jobs_pkey PRIMARY KEY (job_id);

-- (schema_migrations PK comes from the runner-side CREATE TABLE.)

-- Name: session_runtime_overrides session_runtime_overrides_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.session_runtime_overrides
    ADD CONSTRAINT session_runtime_overrides_pkey PRIMARY KEY (tenant_id, session_id);

-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (session_id);

-- Name: tenant_integrations tenant_integrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenant_integrations
    ADD CONSTRAINT tenant_integrations_pkey PRIMARY KEY (tenant_id, integration_id);

-- Name: tenant_memberships tenant_memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenant_memberships
    ADD CONSTRAINT tenant_memberships_pkey PRIMARY KEY (tenant_id, user_id);

-- Name: tenant_org_settings tenant_org_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenant_org_settings
    ADD CONSTRAINT tenant_org_settings_pkey PRIMARY KEY (tenant_id);

-- Name: tenant_settings tenant_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenant_settings
    ADD CONSTRAINT tenant_settings_pkey PRIMARY KEY (tenant_id);

-- Name: tenants tenants_custom_domain_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_custom_domain_key UNIQUE (custom_domain);

-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (tenant_id);

-- Name: tenants tenants_slug_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_slug_key UNIQUE (slug);

-- Name: tenants tenants_workos_org_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_workos_org_id_key UNIQUE (workos_org_id);

-- Name: tool_events tool_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_events
    ADD CONSTRAINT tool_events_pkey PRIMARY KEY (id);

-- Name: tool_execution_contexts tool_execution_contexts_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_execution_contexts
    ADD CONSTRAINT tool_execution_contexts_pkey PRIMARY KEY (id);

-- Name: tool_execution_contexts tool_execution_contexts_tool_context_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_execution_contexts
    ADD CONSTRAINT tool_execution_contexts_tool_context_id_key UNIQUE (tool_context_id);

-- Name: user_github_connections user_github_connections_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_github_connections
    ADD CONSTRAINT user_github_connections_pkey PRIMARY KEY (tenant_id, user_id);

-- Name: user_microsoft_connections user_microsoft_connections_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_microsoft_connections
    ADD CONSTRAINT user_microsoft_connections_pkey PRIMARY KEY (tenant_id, user_id);

-- Name: user_notion_connections user_notion_connections_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_notion_connections
    ADD CONSTRAINT user_notion_connections_pkey PRIMARY KEY (tenant_id, user_id);

-- Name: user_settings_sections user_settings_sections_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_settings_sections
    ADD CONSTRAINT user_settings_sections_pkey PRIMARY KEY (tenant_id, user_id, section_key);

-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

-- Name: users users_workos_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_workos_user_id_key UNIQUE (workos_user_id);

-- Name: idx_admin_mcp_servers_enabled; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_admin_mcp_servers_enabled ON public.admin_mcp_servers USING btree (enabled, updated_at DESC);

-- Name: idx_admin_mcp_servers_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_admin_mcp_servers_tenant ON public.admin_mcp_servers USING btree (tenant_id, enabled);

-- Name: idx_admin_skill_revisions_review_status; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_admin_skill_revisions_review_status ON public.admin_skill_revisions USING btree (review_status, created_at DESC);

-- Name: idx_admin_skill_revisions_skill_created; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_admin_skill_revisions_skill_created ON public.admin_skill_revisions USING btree (skill_id, created_at DESC);

-- Name: idx_admin_skill_revisions_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_admin_skill_revisions_tenant ON public.admin_skill_revisions USING btree (tenant_id, skill_id);

-- Name: idx_admin_skills_active_revision; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_admin_skills_active_revision ON public.admin_skills USING btree (active_revision_id);

-- Name: idx_admin_skills_enabled; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_admin_skills_enabled ON public.admin_skills USING btree (enabled, updated_at DESC);

-- Name: idx_admin_skills_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_admin_skills_tenant ON public.admin_skills USING btree (tenant_id, enabled);

-- Name: idx_approvals_session_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_approvals_session_id ON public.approvals USING btree (session_id, user_id, status, created_at);

-- Name: idx_approvals_tenant_session; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_approvals_tenant_session ON public.approvals USING btree (tenant_id, session_id);

-- Name: idx_approvals_stale_sweep; Type: INDEX; Schema: public; Owner: -
-- Partial index supporting the startup / background sweep of stale pending
-- approvals: only `pending` rows are ever swept, so indexing just those keeps
-- the index tiny and the "find rows past their deadline" scan cheap.

CREATE INDEX idx_approvals_stale_sweep ON public.approvals USING btree (expires_at) WHERE (status = 'pending'::text);

-- Name: idx_artifact_download_tokens_lookup; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_artifact_download_tokens_lookup ON public.artifact_download_tokens USING btree (token, user_id, expires_at);

-- Name: idx_artifact_download_tokens_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_artifact_download_tokens_tenant ON public.artifact_download_tokens USING btree (tenant_id, artifact_id);

-- Name: idx_artifacts_session_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_artifacts_session_id ON public.artifacts USING btree (session_id, user_id, created_at DESC);

-- Name: idx_artifacts_source_artifact_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_artifacts_source_artifact_id ON public.artifacts USING btree (source_artifact_id);

-- Name: idx_artifacts_tenant_session; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_artifacts_tenant_session ON public.artifacts USING btree (tenant_id, session_id);

-- Name: idx_audit_events_session_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_audit_events_session_id ON public.audit_events USING btree (session_id, user_id, created_at);

-- Name: idx_audit_events_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_audit_events_tenant ON public.audit_events USING btree (tenant_id, user_id, created_at);

-- Name: idx_message_tool_results_message_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_message_tool_results_message_id ON public.message_tool_results USING btree (message_id, created_at, id);

-- Name: idx_message_tool_results_session_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_message_tool_results_session_id ON public.message_tool_results USING btree (session_id, created_at, id);

-- Name: idx_message_tool_results_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_message_tool_results_tenant ON public.message_tool_results USING btree (tenant_id, session_id);

-- Name: idx_messages_feedback_rating; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_messages_feedback_rating ON public.messages USING btree (tenant_id, feedback_rating, created_at) WHERE (feedback_rating IS NOT NULL);

-- Name: idx_messages_pii_status; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_messages_pii_status ON public.messages USING btree (tenant_id, (((detail_json -> 'pii'::text) ->> 'status'::text)));

-- Name: idx_messages_session_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_messages_session_id ON public.messages USING btree (session_id);

-- Name: idx_messages_tenant_session; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_messages_tenant_session ON public.messages USING btree (tenant_id, session_id);

-- Name: idx_pii_scan_jobs_due; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_pii_scan_jobs_due ON public.pii_scan_jobs USING btree (status, run_after) WHERE (status = 'queued'::text);

-- Name: idx_pii_scan_jobs_scan_run; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_pii_scan_jobs_scan_run ON public.pii_scan_jobs USING btree (tenant_id, scan_run_id);

-- Name: idx_pii_scan_runs_status; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_pii_scan_runs_status ON public.pii_scan_runs USING btree (tenant_id, status, created_at DESC);

-- Name: idx_pii_scan_runs_subject; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_pii_scan_runs_subject ON public.pii_scan_runs USING btree (tenant_id, subject_type, subject_id, created_at DESC);

-- Name: idx_platform_events_type_created; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_platform_events_type_created ON public.platform_events USING btree (event_type, created_at DESC);

-- Name: idx_resource_activations_resource; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_resource_activations_resource ON public.resource_activations USING btree (tenant_id, resource_type, resource_id, occurred_at DESC);

-- Name: idx_resource_activations_session; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_resource_activations_session ON public.resource_activations USING btree (session_id);

-- Name: idx_resource_activations_session_message; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_resource_activations_session_message ON public.resource_activations USING btree (tenant_id, session_id, message_id);

-- Name: idx_runtime_sessions_session_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_runtime_sessions_session_id ON public.runtime_sessions USING btree (session_id);

-- Name: idx_runtime_sessions_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_runtime_sessions_tenant ON public.runtime_sessions USING btree (tenant_id, user_id);

-- Name: idx_scheduled_job_runs_job_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_scheduled_job_runs_job_id ON public.scheduled_job_runs USING btree (job_id, created_at DESC);

-- Name: idx_scheduled_job_runs_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_scheduled_job_runs_tenant ON public.scheduled_job_runs USING btree (tenant_id, job_id);

-- Name: idx_scheduled_job_runs_user_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_scheduled_job_runs_user_id ON public.scheduled_job_runs USING btree (user_id, created_at DESC);

-- Name: idx_scheduled_jobs_next_run_at; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_scheduled_jobs_next_run_at ON public.scheduled_jobs USING btree (enabled, next_run_at);

-- Name: idx_scheduled_jobs_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_scheduled_jobs_tenant ON public.scheduled_jobs USING btree (tenant_id, user_id);

-- Name: idx_scheduled_jobs_user_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_scheduled_jobs_user_id ON public.scheduled_jobs USING btree (user_id, updated_at DESC);

-- Name: idx_sessions_tenant_purpose; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_sessions_tenant_purpose ON public.sessions USING btree (tenant_id, purpose) WHERE (purpose <> 'normal'::text);

-- Name: idx_sessions_tenant_user; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_sessions_tenant_user ON public.sessions USING btree (tenant_id, user_id);

-- Name: idx_sessions_user_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_sessions_user_id ON public.sessions USING btree (user_id);

-- Name: idx_tenant_integrations_enabled; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_tenant_integrations_enabled ON public.tenant_integrations USING btree (tenant_id) WHERE (reads_enabled OR writes_enabled);

-- Name: idx_tenant_memberships_user; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_tenant_memberships_user ON public.tenant_memberships USING btree (user_id);

-- Name: idx_tool_events_session_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_tool_events_session_id ON public.tool_events USING btree (session_id, user_id, created_at);

-- Name: idx_tool_events_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_tool_events_tenant ON public.tool_events USING btree (tenant_id, session_id);

-- Name: idx_tool_execution_contexts_session_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_tool_execution_contexts_session_id ON public.tool_execution_contexts USING btree (session_id, user_id, expires_at);

-- Name: idx_tool_execution_contexts_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_tool_execution_contexts_tenant ON public.tool_execution_contexts USING btree (tenant_id, session_id);

-- Name: idx_user_github_connections_login; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_user_github_connections_login ON public.user_github_connections USING btree (tenant_id, github_login);

-- Name: idx_user_microsoft_connections_email; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_user_microsoft_connections_email ON public.user_microsoft_connections USING btree (tenant_id, microsoft_email);

-- Name: idx_user_notion_connections_workspace; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_user_notion_connections_workspace ON public.user_notion_connections USING btree (tenant_id, notion_workspace_id);

-- Name: idx_user_settings_sections_updated_at; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_user_settings_sections_updated_at ON public.user_settings_sections USING btree (updated_at DESC);

-- Name: idx_user_settings_tenant; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_user_settings_tenant ON public.user_settings_sections USING btree (tenant_id, user_id);

-- Name: admin_mcp_servers admin_mcp_servers_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin_mcp_servers
    ADD CONSTRAINT admin_mcp_servers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: admin_skill_revisions admin_skill_revisions_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin_skill_revisions
    ADD CONSTRAINT admin_skill_revisions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: admin_skill_revisions admin_skill_revisions_tenant_skill_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin_skill_revisions
    ADD CONSTRAINT admin_skill_revisions_tenant_skill_id_fkey FOREIGN KEY (tenant_id, skill_id) REFERENCES public.admin_skills(tenant_id, skill_id) ON DELETE CASCADE;

-- Name: admin_skills admin_skills_active_revision_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin_skills
    ADD CONSTRAINT admin_skills_active_revision_id_fkey FOREIGN KEY (active_revision_id) REFERENCES public.admin_skill_revisions(skill_revision_id) ON DELETE SET NULL;

-- Name: admin_skills admin_skills_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.admin_skills
    ADD CONSTRAINT admin_skills_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: approvals approvals_runtime_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_runtime_id_fkey FOREIGN KEY (runtime_id) REFERENCES public.runtime_sessions(runtime_id) ON DELETE CASCADE;

-- Name: approvals approvals_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE CASCADE;

-- Name: approvals approvals_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: approvals approvals_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: artifact_download_tokens artifact_download_tokens_artifact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifact_download_tokens
    ADD CONSTRAINT artifact_download_tokens_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.artifacts(artifact_id) ON DELETE CASCADE;

-- Name: artifact_download_tokens artifact_download_tokens_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifact_download_tokens
    ADD CONSTRAINT artifact_download_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE CASCADE;

-- Name: artifact_download_tokens artifact_download_tokens_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifact_download_tokens
    ADD CONSTRAINT artifact_download_tokens_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: artifact_download_tokens artifact_download_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifact_download_tokens
    ADD CONSTRAINT artifact_download_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: artifacts artifacts_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE CASCADE;

-- Name: artifacts artifacts_source_artifact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_source_artifact_id_fkey FOREIGN KEY (source_artifact_id) REFERENCES public.artifacts(artifact_id) ON DELETE SET NULL;

-- Name: artifacts artifacts_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: artifacts artifacts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: audit_events audit_events_approval_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_approval_id_fkey FOREIGN KEY (approval_id) REFERENCES public.approvals(approval_id) ON DELETE SET NULL;

-- Name: audit_events audit_events_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE SET NULL;

-- Name: audit_events audit_events_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: audit_events audit_events_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;

-- Name: message_tool_results message_tool_results_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.message_tool_results
    ADD CONSTRAINT message_tool_results_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(message_id) ON DELETE CASCADE;

-- Name: message_tool_results message_tool_results_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.message_tool_results
    ADD CONSTRAINT message_tool_results_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE CASCADE;

-- Name: message_tool_results message_tool_results_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.message_tool_results
    ADD CONSTRAINT message_tool_results_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: message_tool_results message_tool_results_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.message_tool_results
    ADD CONSTRAINT message_tool_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: messages messages_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id);

-- Name: messages messages_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: messages messages_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);

-- Name: pii_scan_jobs pii_scan_jobs_scan_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.pii_scan_jobs
    ADD CONSTRAINT pii_scan_jobs_scan_run_id_fkey FOREIGN KEY (scan_run_id) REFERENCES public.pii_scan_runs(scan_run_id) ON DELETE CASCADE;

-- Name: pii_scan_jobs pii_scan_jobs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.pii_scan_jobs
    ADD CONSTRAINT pii_scan_jobs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: pii_scan_runs pii_scan_runs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.pii_scan_runs
    ADD CONSTRAINT pii_scan_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: resource_activations resource_activations_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.resource_activations
    ADD CONSTRAINT resource_activations_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(message_id) ON DELETE SET NULL;

-- Name: resource_activations resource_activations_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.resource_activations
    ADD CONSTRAINT resource_activations_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE CASCADE;

-- Name: resource_activations resource_activations_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.resource_activations
    ADD CONSTRAINT resource_activations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: runtime_sessions runtime_sessions_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.runtime_sessions
    ADD CONSTRAINT runtime_sessions_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id);

-- Name: runtime_sessions runtime_sessions_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.runtime_sessions
    ADD CONSTRAINT runtime_sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: runtime_sessions runtime_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.runtime_sessions
    ADD CONSTRAINT runtime_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);

-- Name: scheduled_job_runs scheduled_job_runs_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.scheduled_job_runs
    ADD CONSTRAINT scheduled_job_runs_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.scheduled_jobs(job_id) ON DELETE CASCADE;

-- Name: scheduled_job_runs scheduled_job_runs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.scheduled_job_runs
    ADD CONSTRAINT scheduled_job_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: scheduled_jobs scheduled_jobs_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.scheduled_jobs
    ADD CONSTRAINT scheduled_jobs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: scheduled_jobs scheduled_jobs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.scheduled_jobs
    ADD CONSTRAINT scheduled_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: session_runtime_overrides session_runtime_overrides_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.session_runtime_overrides
    ADD CONSTRAINT session_runtime_overrides_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id);

-- Name: session_runtime_overrides session_runtime_overrides_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.session_runtime_overrides
    ADD CONSTRAINT session_runtime_overrides_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE CASCADE;

-- Name: session_runtime_overrides session_runtime_overrides_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.session_runtime_overrides
    ADD CONSTRAINT session_runtime_overrides_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: sessions sessions_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: sessions sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);

-- Name: tenant_integrations tenant_integrations_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenant_integrations
    ADD CONSTRAINT tenant_integrations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id) ON DELETE CASCADE;

-- Name: tenant_integrations tenant_integrations_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenant_integrations
    ADD CONSTRAINT tenant_integrations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(user_id);

-- Name: tenant_memberships tenant_memberships_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenant_memberships
    ADD CONSTRAINT tenant_memberships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id) ON DELETE CASCADE;

-- Name: tenant_memberships tenant_memberships_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenant_memberships
    ADD CONSTRAINT tenant_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: tenant_org_settings tenant_org_settings_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenant_org_settings
    ADD CONSTRAINT tenant_org_settings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id) ON DELETE CASCADE;

-- Name: tenant_settings tenant_settings_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tenant_settings
    ADD CONSTRAINT tenant_settings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: tool_events tool_events_approval_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_events
    ADD CONSTRAINT tool_events_approval_id_fkey FOREIGN KEY (approval_id) REFERENCES public.approvals(approval_id) ON DELETE SET NULL;

-- Name: tool_events tool_events_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_events
    ADD CONSTRAINT tool_events_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(message_id) ON DELETE SET NULL;

-- Name: tool_events tool_events_runtime_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_events
    ADD CONSTRAINT tool_events_runtime_id_fkey FOREIGN KEY (runtime_id) REFERENCES public.runtime_sessions(runtime_id) ON DELETE CASCADE;

-- Name: tool_events tool_events_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_events
    ADD CONSTRAINT tool_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE CASCADE;

-- Name: tool_events tool_events_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_events
    ADD CONSTRAINT tool_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: tool_events tool_events_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_events
    ADD CONSTRAINT tool_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: tool_execution_contexts tool_execution_contexts_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_execution_contexts
    ADD CONSTRAINT tool_execution_contexts_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(message_id) ON DELETE SET NULL;

-- Name: tool_execution_contexts tool_execution_contexts_runtime_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_execution_contexts
    ADD CONSTRAINT tool_execution_contexts_runtime_id_fkey FOREIGN KEY (runtime_id) REFERENCES public.runtime_sessions(runtime_id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Name: tool_execution_contexts tool_execution_contexts_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_execution_contexts
    ADD CONSTRAINT tool_execution_contexts_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id) ON DELETE CASCADE;

-- Name: tool_execution_contexts tool_execution_contexts_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_execution_contexts
    ADD CONSTRAINT tool_execution_contexts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: tool_execution_contexts tool_execution_contexts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.tool_execution_contexts
    ADD CONSTRAINT tool_execution_contexts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: user_github_connections user_github_connections_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_github_connections
    ADD CONSTRAINT user_github_connections_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: user_github_connections user_github_connections_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_github_connections
    ADD CONSTRAINT user_github_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: user_microsoft_connections user_microsoft_connections_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_microsoft_connections
    ADD CONSTRAINT user_microsoft_connections_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: user_microsoft_connections user_microsoft_connections_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_microsoft_connections
    ADD CONSTRAINT user_microsoft_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: user_notion_connections user_notion_connections_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_notion_connections
    ADD CONSTRAINT user_notion_connections_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: user_notion_connections user_notion_connections_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_notion_connections
    ADD CONSTRAINT user_notion_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: user_settings_sections user_settings_sections_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_settings_sections
    ADD CONSTRAINT user_settings_sections_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(tenant_id);

-- Name: user_settings_sections user_settings_sections_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.user_settings_sections
    ADD CONSTRAINT user_settings_sections_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

-- Name: admin_mcp_servers; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.admin_mcp_servers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_mcp_servers FORCE ROW LEVEL SECURITY;

-- Name: admin_mcp_servers admin_mcp_servers_tenant_delete; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_mcp_servers_tenant_delete ON public.admin_mcp_servers FOR DELETE USING ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: admin_mcp_servers admin_mcp_servers_tenant_insert; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_mcp_servers_tenant_insert ON public.admin_mcp_servers FOR INSERT WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: admin_mcp_servers admin_mcp_servers_tenant_read; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_mcp_servers_tenant_read ON public.admin_mcp_servers FOR SELECT USING (((tenant_id = current_setting('app.current_tenant_id'::text, true)) OR (tenant_id = 'system'::text)));

-- Name: admin_mcp_servers admin_mcp_servers_tenant_update; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_mcp_servers_tenant_update ON public.admin_mcp_servers FOR UPDATE USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: admin_skill_revisions; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.admin_skill_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_skill_revisions FORCE ROW LEVEL SECURITY;

-- Name: admin_skill_revisions admin_skill_revisions_tenant_delete; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_skill_revisions_tenant_delete ON public.admin_skill_revisions FOR DELETE USING ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: admin_skill_revisions admin_skill_revisions_tenant_insert; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_skill_revisions_tenant_insert ON public.admin_skill_revisions FOR INSERT WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: admin_skill_revisions admin_skill_revisions_tenant_read; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_skill_revisions_tenant_read ON public.admin_skill_revisions FOR SELECT USING (((tenant_id = current_setting('app.current_tenant_id'::text, true)) OR (tenant_id = 'system'::text)));

-- Name: admin_skill_revisions admin_skill_revisions_tenant_update; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_skill_revisions_tenant_update ON public.admin_skill_revisions FOR UPDATE USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: admin_skills; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.admin_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_skills FORCE ROW LEVEL SECURITY;

-- Name: admin_skills admin_skills_tenant_delete; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_skills_tenant_delete ON public.admin_skills FOR DELETE USING ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: admin_skills admin_skills_tenant_insert; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_skills_tenant_insert ON public.admin_skills FOR INSERT WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: admin_skills admin_skills_tenant_read; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_skills_tenant_read ON public.admin_skills FOR SELECT USING (((tenant_id = current_setting('app.current_tenant_id'::text, true)) OR (tenant_id = 'system'::text)));

-- Name: admin_skills admin_skills_tenant_update; Type: POLICY; Schema: public; Owner: -

CREATE POLICY admin_skills_tenant_update ON public.admin_skills FOR UPDATE USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: approvals; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approvals FORCE ROW LEVEL SECURITY;

-- Name: approvals approvals_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY approvals_tenant_isolation ON public.approvals USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: artifact_download_tokens; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.artifact_download_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artifact_download_tokens FORCE ROW LEVEL SECURITY;

-- Name: artifact_download_tokens artifact_download_tokens_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY artifact_download_tokens_tenant_isolation ON public.artifact_download_tokens USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: artifacts; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artifacts FORCE ROW LEVEL SECURITY;

-- Name: artifacts artifacts_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY artifacts_tenant_isolation ON public.artifacts USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: audit_events; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events FORCE ROW LEVEL SECURITY;

-- Name: audit_events audit_events_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY audit_events_tenant_isolation ON public.audit_events USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: audit_events audit_events_append_only; Type: POLICY; Schema: public; Owner: -
-- The audit log is append-only. The tenant-isolation policy above is permissive
-- and unqualified (applies to ALL commands), which by itself would let an
-- application-role caller UPDATE or DELETE their own tenant's audit rows. These
-- RESTRICTIVE policies are AND-ed with every other policy, so a USING(false)
-- restrictive policy hard-denies UPDATE and DELETE for the RLS-bound app role no
-- matter what permissive policies exist now or are added later. Migrations run
-- as a BYPASSRLS superuser, so legitimate retention/GC jobs are unaffected.

CREATE POLICY audit_events_no_update ON public.audit_events AS RESTRICTIVE FOR UPDATE USING (false);

CREATE POLICY audit_events_no_delete ON public.audit_events AS RESTRICTIVE FOR DELETE USING (false);

-- Name: message_tool_results; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.message_tool_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_tool_results FORCE ROW LEVEL SECURITY;

-- Name: message_tool_results message_tool_results_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY message_tool_results_tenant_isolation ON public.message_tool_results USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: messages; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages FORCE ROW LEVEL SECURITY;

-- Name: messages messages_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY messages_tenant_isolation ON public.messages USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: pii_scan_jobs; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.pii_scan_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pii_scan_jobs FORCE ROW LEVEL SECURITY;

-- Name: pii_scan_jobs pii_scan_jobs_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY pii_scan_jobs_tenant_isolation ON public.pii_scan_jobs USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: pii_scan_runs; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.pii_scan_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pii_scan_runs FORCE ROW LEVEL SECURITY;

-- Name: pii_scan_runs pii_scan_runs_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY pii_scan_runs_tenant_isolation ON public.pii_scan_runs USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: resource_activations; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.resource_activations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_activations FORCE ROW LEVEL SECURITY;

-- Name: resource_activations resource_activations_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY resource_activations_tenant_isolation ON public.resource_activations USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: runtime_sessions; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.runtime_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.runtime_sessions FORCE ROW LEVEL SECURITY;

-- Name: runtime_sessions runtime_sessions_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY runtime_sessions_tenant_isolation ON public.runtime_sessions USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: scheduled_job_runs; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.scheduled_job_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_job_runs FORCE ROW LEVEL SECURITY;

-- Name: scheduled_job_runs scheduled_job_runs_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY scheduled_job_runs_tenant_isolation ON public.scheduled_job_runs USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: scheduled_jobs; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.scheduled_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_jobs FORCE ROW LEVEL SECURITY;

-- Name: scheduled_jobs scheduled_jobs_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY scheduled_jobs_tenant_isolation ON public.scheduled_jobs USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: session_runtime_overrides; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.session_runtime_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_runtime_overrides FORCE ROW LEVEL SECURITY;

-- Name: session_runtime_overrides session_runtime_overrides_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY session_runtime_overrides_tenant_isolation ON public.session_runtime_overrides USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: sessions; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions FORCE ROW LEVEL SECURITY;

-- Name: sessions sessions_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY sessions_tenant_isolation ON public.sessions USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: tenant_integrations; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.tenant_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_integrations FORCE ROW LEVEL SECURITY;

-- Name: tenant_integrations tenant_integrations_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY tenant_integrations_tenant_isolation ON public.tenant_integrations USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: tenant_memberships; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.tenant_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_memberships FORCE ROW LEVEL SECURITY;

-- Name: tenant_memberships tenant_memberships_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY tenant_memberships_tenant_isolation ON public.tenant_memberships USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: tenant_org_settings; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.tenant_org_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_org_settings FORCE ROW LEVEL SECURITY;

-- Name: tenant_org_settings tenant_org_settings_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY tenant_org_settings_tenant_isolation ON public.tenant_org_settings USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: tenant_settings; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.tenant_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_settings FORCE ROW LEVEL SECURITY;

-- Name: tenant_settings tenant_settings_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY tenant_settings_isolation ON public.tenant_settings USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: tenants; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenants FORCE ROW LEVEL SECURITY;

-- Name: tenants tenants_self_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY tenants_self_isolation ON public.tenants USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: tool_events; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.tool_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tool_events FORCE ROW LEVEL SECURITY;

-- Name: tool_events tool_events_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY tool_events_tenant_isolation ON public.tool_events USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: tool_execution_contexts; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.tool_execution_contexts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tool_execution_contexts FORCE ROW LEVEL SECURITY;

-- Name: tool_execution_contexts tool_execution_contexts_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY tool_execution_contexts_tenant_isolation ON public.tool_execution_contexts USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: user_github_connections; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.user_github_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_github_connections FORCE ROW LEVEL SECURITY;

-- Name: user_github_connections user_github_connections_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY user_github_connections_tenant_isolation ON public.user_github_connections USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: user_microsoft_connections; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.user_microsoft_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_microsoft_connections FORCE ROW LEVEL SECURITY;

-- Name: user_microsoft_connections user_microsoft_connections_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY user_microsoft_connections_tenant_isolation ON public.user_microsoft_connections USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: user_notion_connections; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.user_notion_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notion_connections FORCE ROW LEVEL SECURITY;

-- Name: user_notion_connections user_notion_connections_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY user_notion_connections_tenant_isolation ON public.user_notion_connections USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));

-- Name: user_settings_sections; Type: ROW SECURITY; Schema: public; Owner: -

ALTER TABLE public.user_settings_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings_sections FORCE ROW LEVEL SECURITY;

-- Name: user_settings_sections user_settings_sections_tenant_isolation; Type: POLICY; Schema: public; Owner: -

CREATE POLICY user_settings_sections_tenant_isolation ON public.user_settings_sections USING ((tenant_id = current_setting('app.current_tenant_id'::text, true))) WITH CHECK ((tenant_id = current_setting('app.current_tenant_id'::text, true)));
